keys:
  - &user_lewelove age1fsyj8whkph3xdvadrk0jycnkfwd70shah5sxksh59qcefthp648sks0djm
  - &host_lab age1288u3z7scjue5yxvsnyztn72zlg6qvxtg2sn58qsu70t5c5z0sfs7d4kym

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *user_lewelove
          - *host_lab

