[storage]
library_root = "/run/media/lewelove/1000xhome/backup-everything/FB2K/Library Historyfied!/"
environment = "~/.secrets/vellum.env"


[theme]
thumbnail_size = 190

[theme.shader]
order = "original"
path = "shaders/mountain_eq.frag"
speed = 0.7
zoom = 0.9
blur = 0.8
grain = 0.1

# path = "shaders/simplex.frag"
# speed = 0.005
# zoom = 0.8
# blur = 0.00


[actions]
get-lyrics = "./scripts/get_lyrics/result/bin/get_lyrics"
search-cover = "./scripts/search_cover/result/bin/search_cover"
cover-palette = "./scripts/cover_palette/target/release/cover_palette"

[manifest]
supported_extensions = [ ".flac" ]


[compiler]
date_added = [ "date_added_youtube", "date_added_applemusic", "date_added_foobar" ]
manifests = [ "mbid.toml", "cover_palette.toml" ]
file_subset_match = [
  "album", "albumartist", "date", "genre",
  "comment", "title", "artist", "tracknumber",
  "musicbrainz_albumartistid", "musicbrainz_albumid",
  "musicbrainz_releasegroupid", "musicbrainz_artistid",
  "musicbrainz_releasetrackid", "musicbrainz_trackid"
]


[compiler.covers]
thumbnail = { interpolation = "lanczos", size = 200 }
modal = { interpolation = "mitchell", size = 627 }


[manifest.keys]
albumartist = { level = "album", newline = true }
album = { level = "album" }
date = { level = "album" }

genre = { level = "album", type = "list", newline = true }
styles = { level = "album", type = "list" }

original_date = { level = "album", newline = true }

country = { level = "album", newline = true }
label = { level = "album" }
catalognumber = { level = "album" }
release_date = { level = "album" }

discogs_url = { level = "album", newline = true, manifests = "url" }
musicbrainz_url = { level = "album", manifests = "url" }
ctdbid_url = { level = "album", manifests = "url" }

tracknumber = { level = "track" }
title = { level = "track" }


[compiler.keys.album]
albumartists = { type = "array" }
styles = { type = "array" }
country = { type = "string" }
label = { type = "string" }
catalognumber = { type = "string" }
media = { type = "string" }
discogs_url = { type = "url" }
musicbrainz_url = { type = "url" }
ctdbid_url = { type = "url" }
date_added_foobar = { type = "datetime" }
date_added_applemusic = { type = "datetime" }
date_added_youtube = { type = "datetime" }
custom_id = { type = "string" }
custom_albumartist = { type = "string", args = "custom_albumartist,artistartist,albumartist" }
custom_string = { type = "string" }
old_comment = { type = "string" }
collection = { type = "array" }
shelves = { type = "array" }
my_year = { type = "array" }
replaygain_album_gain = { type = "string" }
replaygain_album_peak = { type = "string" }
musicbrainz_albumid = { type = "string" }
musicbrainz_albumartistid = { type = "string" }
musicbrainz_releasegroupid = { type = "string" }
cover_palette = { type = "array" }

cover_chroma = { type = "function" }
cover_entropy = { type = "function" }

[compiler.keys.tracks]
lyrics = { type = "string" }
accuripid = { type = "string" }
ctdbid = { type = "string" }
discid = { type = "string" }
instrumental = { type = "boolean" }
replaygain_track_gain = { type = "string" }
replaygain_track_peak = { type = "string" }
musicbrainz_trackid = { type = "string" }
musicbrainz_releasetrackid = { type = "string" }
musicbrainz_artistid = { type = "array" }
# cover_palette = { level = "album", class = "function", args = "k=12,noise=0.0,conv=0.05,filter=0.002,bias=0.0" }
# cover_palette = { level = "album", class = "function", args = "type=kmeans,sort=C,k=8" }
# cover_palette = { level = "album", class = "function", args = "type=kmeans,sort=gradient,k=8,Hb=35,Ht=108,Cb=12,Ct=60,Tb=0,Tt=50" }
# cover_palette = { level = "album", class = "function", args = "type=msc,k=16,bw=0.08,mt=0.05,cg=3.0,t=0.002" }
# cover_palette = { level = "album", class = "function", args = "type=mmcq,k=8,sort=C" }
# cover_palette = { level = "album", class = "function", args = "type=auto,theme=basic,t=0.0,k=12" }
# cover_palette = { level = "album", class = "function", args = "type=msc,bw=6" }
