# -- GROUPERS --

[groupers.genre]
label = "Genre"
select = "${album.genre}"

[groupers.artists]
label = "Artists"
select = "COALESCE(NULLIF(${album.tags.albumartists}, {[]}), ${album.albumartist})"
index = true

[groupers.decade]
label = "Decade"
select = "substr(${album.date}, 1, 3) || {0s}"

[groupers.total_tracks]
label = "Total Tracks"
select = "CAST(${album.info.total_tracks} AS TEXT)"

[groupers.total_discs]
label = "Total Discs"
select = "CAST(COALESCE(${album.info.total_discs}, 1) AS TEXT)"

[groupers.year_added]
label = "Year Added"
select = "substr(${album.info.date_added}, 1, 4)"

[groupers.chroma]
label = "Chroma"
select = "CASE WHEN CAST(${album.tags.cover_chroma} AS FLOAT) = 0 THEN {Monochrome} WHEN CAST(${album.tags.cover_chroma} AS FLOAT) < 15 THEN {Bleak} WHEN CAST(${album.tags.cover_chroma} AS FLOAT) < 33 THEN {Muted} WHEN CAST(${album.tags.cover_chroma} AS FLOAT) < 60 THEN {Standard} ELSE {Vibrant} END"

# -- SORTERS --

[sorters.default]
label = "Default"
order_by = "CASE WHEN LOWER(COALESCE(${album.tags.custom_albumartist}, ${album.albumartist})) LIKE {the %} THEN SUBSTR(COALESCE(${album.tags.custom_albumartist}, ${album.albumartist}), 5) ELSE COALESCE(${album.tags.custom_albumartist}, ${album.albumartist}) END ASC, ${album.date} ASC, ${album.album} ASC"

[sorters.az]
label = "Alphabetical"
order_by = "${album.album} ASC"

[sorters.year]
label = "Year"
order_by = "${album.date} DESC"

[sorters.duration]
label = "Duration"
order_by = "CAST(${album.info.album_duration} AS INT) DESC"

[sorters.chroma]
label = "Chroma"
order_by = "CAST(${album.tags.cover_chroma} AS FLOAT) DESC"

[sorters.entropy]
label = "Entropy"
order_by = "CAST(${album.tags.cover_entropy} AS INT) DESC"

[sorters.date_added]
label = "Date Added"
order_by = "${album.info.date_added} DESC"

[sorters.last_edited]
label = "Last Edited"
order_by = "COALESCE(${album.info.metadata_toml_mtime}, 0) DESC"

# -- COLLECTIONS --

# [collections.library]
# label = "Entire Library"
# filter = "1=1"

[collections.album_library]
label = "Main Library"
filter = "COALESCE(${album.tags.collection}, '') NOT LIKE %{Vapor Memory} AND ${album.genre} NOT LIKE %{Signalwave} AND ${album.genre} NOT LIKE %{Vaporwave}"

[collections.vapor_memory]
label = "Vapor Memory"
filter = "COALESCE(${album.tags.collection}, '') LIKE %{Vapor Memory} OR ${album.genre} LIKE %{Vaporwave}"

[collections.signalwave]
label = "Signal Memory"
filter = "COALESCE(${album.genre}, '') LIKE %{Signalwave}"

# Apple Music Collection

[collections.apple_music]
label = "Apple Music"
filter = "${album.tags.unix_added_applemusic} IS NOT NULL"
strict = true
groupers = ["year_added_applemusic", "genre", "decade"]
sorters = ["unix_added_applemusic", "default", "az", "year"]

[groupers.year_added_applemusic]
label = "Year Added"
select = "substr(${album.tags.unix_added_applemusic}, 1, 4)"
strict = true

[sorters.unix_added_applemusic]
label = "Date Added"
order_by = "${album.tags.unix_added_applemusic} DESC"
strict = true

# Foobar2000 Collection

[collections.foobar]
label = "Foobar2000"
filter = "${album.tags.unix_added_foobar} IS NOT NULL"
strict = true
groupers = ["year_added_foobar"]
sorters = ["unix_added_foobar"]

[groupers.year_added_foobar]
label = "Year Added"
select = "substr(${album.tags.date_added_foobar}, 1, 4)"
strict = true

[sorters.unix_added_foobar]
label = "Date Added"
order_by = "${album.tags.unix_added_foobar} DESC"
strict = true

# My Year

[collections.my_year]
label = "My Year"
filter = "${album.tags.my_year} IS NOT NULL"
strict = true
groupers = ["my_year_grouper"]
sorters = ["default", "date_added"]

[groupers.my_year_grouper]
label = "Year"
select = "${album.tags.my_year}"
strict = true

# -- SHELVES --

[shelves.recently_added]
label = "Recently Added"
filter = "1=1"
order_by = "${album.info.date_added} DESC"

[shelves.ambient50]
label = "Ambient 50"
file = "~/.config/vellum/shelves/Ambient50.txt"

