# FILTERS

# [filters.default]
# label = "Default"
# sql.where = '''
# 1 = 1
# '''

[filters.main_library]
label = "Main Library"
sql.where = '''
COALESCE(${album.keys.collection}, '') NOT LIKE %{Vapor Memory}
AND ${album.keys.genre} NOT LIKE %{Signalwave}
AND ${album.keys.genre} NOT LIKE %{Vaporwave}
AND COALESCE(${album.info.virtual}, 0) != 1
'''

[filters.vapor_memory]
label = "Vapor Memory"
sql.where = '''
(COALESCE(${album.keys.collection}, '') LIKE %{Vapor Memory}
OR ${album.keys.genre} LIKE %{Vaporwave})
'''

[filters.signal_memory]
label = "Signal Memory"
sql.where = '''
COALESCE(${album.keys.genre}, '') LIKE %{Signalwave}
'''

# GROUPERS

[groupers.genre]
label = "Genre"
sql.select = '''
${album.keys.genre}
'''

[groupers.artists]
label = "Artists"
index = true
sql.select = '''
COALESCE(
  NULLIF(${album.keys.albumartists}, {[]}),
  ${album.albumartist}
)
'''

[groupers.decade]
label = "Decade"
sql.select = '''
substr(${album.date}, 1, 3) || {0s}
'''

[groupers.total_tracks]
label = "Total Tracks"
sql.select = '''
CAST(${album.info.total_tracks} AS TEXT)
'''

[groupers.total_discs]
label = "Total Discs"
sql.select = '''
CAST(COALESCE(${album.info.total_discs}, 1) AS TEXT)
'''

[groupers.year_added]
label = "Year Added"
sql.select = '''
substr(${album.keys.date_added}, 1, 4)
'''

[groupers.chroma]
label = "Chroma"
sql.select = '''
CASE
  WHEN CAST(${album.keys.cover_chroma} AS FLOAT) = 0 THEN {Monochrome}
  WHEN CAST(${album.keys.cover_chroma} AS FLOAT) < 15 THEN {Bleak}
  WHEN CAST(${album.keys.cover_chroma} AS FLOAT) < 33 THEN {Muted}
  WHEN CAST(${album.keys.cover_chroma} AS FLOAT) < 60 THEN {Standard}
  ELSE {Vibrant}
END
'''

# ORDERS

[orders.default]
label = "Default"
sql.order_by = '''
CASE
  WHEN LOWER(
    COALESCE(${album.keys.custom_albumartist}, ${album.albumartist})
  ) LIKE {the %}
  THEN SUBSTR(
    COALESCE(${album.keys.custom_albumartist}, ${album.albumartist}),
    5
  )
  ELSE COALESCE(${album.keys.custom_albumartist}, ${album.albumartist})
END ASC,
${album.date} ASC,
${album.album} ASC
'''

[orders.az]
label = "Alphabetical"
sql.order_by = '''
${album.album} ASC
'''

[orders.year]
label = "Year"
sql.order_by = '''
${album.date} DESC
'''

[orders.duration]
label = "Duration"
sql.order_by = '''
CAST(${album.info.duration_milliseconds} AS INT) DESC
'''

[orders.cover_hash]
label = "Random"
sql.order_by = '''
${album.covers.main.file.address} ASC
'''

[orders.chroma]
label = "Chroma"
sql.order_by = '''
CAST(${album.keys.cover_chroma} AS FLOAT) DESC
'''

[orders.entropy]
label = "Entropy"
sql.order_by = '''
CAST(${album.keys.cover_entropy} AS INT) DESC
'''

[orders.date_added]
label = "Date Added"
sql.order_by = '''
${album.keys.date_added} DESC
'''

[orders.last_edited]
label = "Last Edited"
sql.order_by = '''
COALESCE(${album.manifests.metadata.file.mtime}, 0) DESC
'''

# LIBRARIES

[libraries.all_albums]
label = "All Albums"
filters = [ "default", "main_library", "vapor_memory", "signal_memory" ]
sql.where = '''
1 = 1
'''

## Apple Music

[libraries.apple_music]
label = "Apple Music"
strict = true
groupers = ["year_added_applemusic", "genre", "decade"]
orders = ["date_added_applemusic", "default", "az", "year"]
sql.where = '''
${album.keys.date_added_applemusic} IS NOT NULL
'''

[groupers.year_added_applemusic]
label = "Year Added"
strict = true
sql.select = '''
substr(${album.keys.date_added_applemusic}, 1, 4)
'''

[orders.date_added_applemusic]
label = "Date Added"
strict = true
sql.order_by = '''
${album.keys.date_added_applemusic} DESC
'''

## Foobar2000

[libraries.foobar]
label = "Foobar2000"
strict = true
groupers = ["year_added_foobar"]
orders = ["date_added_foobar"]
sql.where = '''
${album.keys.date_added_foobar} IS NOT NULL
'''

[groupers.year_added_foobar]
label = "Year Added"
strict = true
sql.select = '''
substr(${album.keys.date_added_foobar}, 1, 4)
'''

[orders.date_added_foobar]
label = "Date Added"
strict = true
sql.order_by = '''
${album.keys.date_added_foobar} DESC
'''

## My Year

[libraries.my_year]
label = "My Year"
strict = true
groupers = ["my_year_grouper"]
orders = ["default", "date_added"]
sql.where = '''
${album.keys.my_year} IS NOT NULL
'''

[groupers.my_year_grouper]
label = "Year"
strict = true
sql.select = '''
${album.keys.my_year}
'''

# SHELVES

[shelves.virtual]
label = "Virtual Albums"
sql.where = '''
COALESCE(${album.info.virtual}, 0) = 1
'''
sql.order_by = '''
${album.keys.date_added} DESC
'''

[shelves.ambient50]
label = "Ambient 50"
file = "~/.config/vellum/shelves/Ambient50.txt"
