[files]

dale = {
  run = "repomix ~/dev/dale --quiet && repomix ~/.config/dale --quiet",
  paste = [
  "~/Folders/XML Packed/~-dev-dale.xml",
  "~/Folders/XML Packed/~-.config-dale.xml"
  ]
}

nix-config = {
  run = "repomix ~/nix-config --quiet",
  paste = [ "~/Folders/XML Packed/~-nix-config.xml" ]
}

album_curation = {
  run = "repomix ~/dev/album_curation --quiet",
  paste = [
  "~//Folders/XML Packed/~-dev-album_curation.xml",
  ]
}

# mute = {
#   run = "repomix ~/dev/mute --quiet && repomix ~/.config/mute --quiet",
#   paste = [
#   "~/Folders/XML Packed/~-dev-mute.xml",
#   "~/Folders/XML Packed/~-.config-mute.xml"
#   ]
# }
