[files]

nix-config = {
  run = "repomix ~/nix-config --quiet",
  paste = [ "~/Folders/XML Packed/~-nix-config.xml" ]
}

vellum = {
  run = "repomix ~/dev/vellum --quiet && repomix ~/.config/vellum --quiet",
  paste = [
  "~/Folders/XML Packed/~-dev-vellum.xml",
  "~/Folders/XML Packed/~-.config-vellum.xml"
  ]
}

mute = {
  run = "repomix ~/dev/mute --quiet && repomix ~/.config/mute --quiet",
  paste = [
  "~/Folders/XML Packed/~-dev-mute.xml",
  "~/Folders/XML Packed/~-.config-mute.xml"
  ]
}
