ambient50 = [
  "Brian Eno - Ambient 1 (Music For Airports)",
  "Aphex Twin - Selected Ambient Works Volume II",
  "William Basinski - The Disintegration Loops",
  "Terry Riley - A Rainbow in Curved Air",
  "The KLF - Chill Out",
  "Stars of the Lid - The Tired Sounds of Stars of the Lid",
  "Oval - 94 Diskont",
  "Pauline Oliveros, Stuart Dempster, Panaiotis - Deep Listening",
  "Tim Hecker - Harmony in Ultraviolet",
  "Robert Fripp & Brian Eno - Evening Star",
  "Gas - Pop",
  "Laurie Spiegel - The Expanding Universe",
  "Brian Eno (With Daniel Lanois & Roger Eno) - Apollo Atmospheres & Soundtracks",
  "The Caretaker - An Empty Bliss Beyond This World",
  "Robert Ashley - Automatic Writing",
  "Terry Riley - Persian Surgery Dervishes",
  "Alice Coltrane - Turiya Sings",
  "Stars of the Lid - And Their Refinement of the Decline",
  "The Orb - Orbus Terrarum",
  "Oneohtrix Point Never - Replica",
  "Grouper - Alien Observer",
  "Keith Fullerton Whitman - Playthroughs",
  "Brian Eno - Ambient 4 (On Land)",
  "Folke Rabe - What",
  "Pauline Oliveros - Accordion & Voice",
  "David Behrman - On The Other Ocean",
  "Julianna Barwick - The Magic Place",
  "Ashra - New Age Of Earth",
  "Steve Roach - Structures From Silence",
  "Laraaji - Ambient 3 (Day of Radiance)",
  "Tim Hecker - Virgins",
  "Biosphere - Substrata",
  "Suzanne Ciani - Buchla Concerts 1975",
  "Max Richter - Sleep",
  "Harold Budd & Brian Eno - The Pearl",
  "Ekkehard Ehlers - Plays",
  "Eluvium - Talk Amongst The Trees",
  "Huerco S. - For Those Of You Who Have Never (And Also Those Who Have)",
  "Edgar Froese - Epsilon In Malaysian Pale",
  "Jon Hassel - Vernal Equinox",
  "Bing & Ruth - Tomorrow Was the Golden Age",
  "Ernest Hood - Neighborhoods",
  "Deathprod - Morals and Dogma",
]
