#  lewelove hyprland config #

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = systemctl --user start hyprland-session.target

source = ~/.config/hypr/io.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/window-rules.conf
source = ~/.config/hypr/visuals.conf

# source = ~/.config/hypr/modules/.conf

